#DevsecopsProject
name: Governed Terraform Apply

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Write kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Terraform Init
        run: |
          cd iac/terraform/k8s
          terraform init -reconfigure

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: |
          cd iac/terraform/k8s
          terraform plan \
            -var="kubeconfig_path=$HOME/.kube/config" \
            -state=$HOME/terraform-state/k8s/terraform.tfstate

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: |
          cd iac/terraform/k8s
          terraform apply -auto-approve \
            -var="kubeconfig_path=$HOME/.kube/config" \
            -state=$HOME/terraform-state/k8s/terraform.tfstate

